openapi: "3.0.0"
info:
  version: 1.0.0
  title: Anonymous Message Board API
servers:
  - url: http://localhost:8080
    description: Local
paths:
  /api/threads/{board}:
    post:
      operationId: createThread
      parameters:
        - $ref: "#/components/parameters/Board"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/CreateThreadBody"
          application/json:
            schema:
              $ref: "#/components/schemas/CreateThreadBody"
      responses:
        302:
          description: Found
          content:
            text/plain:
              schema:
                description: Thread ID
                type: string
        default:
          $ref: "#/components/responses/Default"
    get:
      operationId: getThreads
      parameters:
        - $ref: "#/components/parameters/Board"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Thread"
        default:
          $ref: "#/components/responses/Default"

  /api/replies/{board}:
    post:
      operationId: createReply
      parameters:
        - $ref: "#/components/parameters/Board"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/CreateReplyBody"
          application/json:
            schema:
              $ref: "#/components/schemas/CreateReplyBody"
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                description: Reply ID
                type: string
        default:
          $ref: "#/components/responses/Default"

components:
  schemas:
    CreateThreadBody:
      type: object
      properties:
        text:
          type: string
        delete_password:
          type: string
      required:
        - text
        - delete_password
    CreateReplyBody:
      type: object
      properties:
        text:
          type: string
        delete_password:
          type: string
        thread_id:
          type: string
      required:
        - text
        - delete_password
        - thread_id

    Reply:
      type: object
      properties:
        _id:
          type: string
        text:
          type: string
      required:
        - _id
        - text

    Thread:
      type: object
      properties:
        _id:
          type: string
        text:
          type: string
        created_on:
          type: string
          format: date-time
        bumped_on:
          type: string
          format: date-time
        replies:
          type: array
          items:
            $ref: "#/components/schemas/Reply"
      required:
        - _id
        - text
        - created_on
        - bumped_on
        - reported
        - replies

  parameters:
    Board:
      name: board
      in: path
      required: true
      schema:
        type: string

  responses:
    Default:
      description: Unexpected server error
      content:
        text/plain:
          schema:
            type: string
