openapi: "3.0.0"
info:
  version: 1.0.0
  title: Anonymous Message Board API
servers:
  - url: http://localhost:8080
    description: Local
paths:
  /api/threads/{board}:
    post:
      summary: Creates a new thread
      operationId: createThread
      parameters:
        - $ref: "#/components/parameters/Board"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/CreateThreadForm"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateThreadResp"
        default:
          $ref: "#/components/responses/Default"

components:
  schemas:
    CreateThreadForm:
      type: object
      properties:
        text:
          type: string
        delete_password:
          type: string
      required:
        - text
        - delete_password

    CreateThreadResp:
      type: object
      properties:
        _id:
          type: string
        text:
          type: string
        created_on:
          type: string
          format: date-time
        bumped_on:
          type: string
          format: date-time
        reported:
          type: boolean
        replies:
          type: array
          items:
            type: string
      required:
        - _id
        - text
        - created_on
        - bumped_on
        - reported
        - replies

  parameters:
    Board:
      name: board
      in: path
      required: true
      schema:
        type: string

  responses:
    Default:
      description: Unexpected server error
      content:
        text/plain:
          schema:
            type: string
